// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

public final class ChordNodeProto {
  private ChordNodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_NotifyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chord_NotifyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_NotifyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chord_NotifyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_FindSuccessorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chord_FindSuccessorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_FindSuccessorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chord_FindSuccessorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_Identifier_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chord_Identifier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026chordNodeService.proto\022\005chord\"6\n\rNotif" +
      "yRequest\022%\n\nidentifier\030\001 \001(\0132\021.chord.Ide" +
      "ntifier\"-\n\016NotifyResponse\022\017\n\007address\030\001 \001" +
      "(\t\022\n\n\002id\030\002 \001(\005\"\"\n\024FindSuccessorRequest\022\n" +
      "\n\002id\030\001 \001(\005\">\n\025FindSuccessorResponse\022%\n\ni" +
      "dentifier\030\001 \001(\0132\021.chord.Identifier\"2\n\nId" +
      "entifier\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\n\n\002id" +
      "\030\003 \001(\0052\231\001\n\020ChordNodeService\0227\n\006Notify\022\024." +
      "chord.NotifyRequest\032\025.chord.NotifyRespon" +
      "se\"\000\022L\n\rFindSuccessor\022\033.chord.FindSucces" +
      "sorRequest\032\034.chord.FindSuccessorResponse" +
      "\"\000B\'\n\016net.grpc.chordB\016ChordNodeProtoP\001\242\002" +
      "\002CNb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_chord_NotifyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chord_NotifyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chord_NotifyRequest_descriptor,
        new String[] { "Identifier", });
    internal_static_chord_NotifyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chord_NotifyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chord_NotifyResponse_descriptor,
        new String[] { "Address", "Id", });
    internal_static_chord_FindSuccessorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chord_FindSuccessorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chord_FindSuccessorRequest_descriptor,
        new String[] { "Id", });
    internal_static_chord_FindSuccessorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chord_FindSuccessorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chord_FindSuccessorResponse_descriptor,
        new String[] { "Identifier", });
    internal_static_chord_Identifier_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chord_Identifier_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chord_Identifier_descriptor,
        new String[] { "Ip", "Port", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
