// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

public interface FindSuccessorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chord.FindSuccessorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
