// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

/**
 * Protobuf type {@code chord.FindSuccessorResponse}
 */
public  final class FindSuccessorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chord.FindSuccessorResponse)
    FindSuccessorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FindSuccessorResponse.newBuilder() to construct.
  private FindSuccessorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FindSuccessorResponse() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FindSuccessorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Identifier.Builder subBuilder = null;
            if (identifier_ != null) {
              subBuilder = identifier_.toBuilder();
            }
            identifier_ = input.readMessage(Identifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(identifier_);
              identifier_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChordNodeProto.internal_static_chord_FindSuccessorResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChordNodeProto.internal_static_chord_FindSuccessorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FindSuccessorResponse.class, Builder.class);
  }

  public static final int IDENTIFIER_FIELD_NUMBER = 1;
  private Identifier identifier_;
  /**
   * <code>.chord.Identifier identifier = 1;</code>
   */
  public boolean hasIdentifier() {
    return identifier_ != null;
  }
  /**
   * <code>.chord.Identifier identifier = 1;</code>
   */
  public Identifier getIdentifier() {
    return identifier_ == null ? Identifier.getDefaultInstance() : identifier_;
  }
  /**
   * <code>.chord.Identifier identifier = 1;</code>
   */
  public IdentifierOrBuilder getIdentifierOrBuilder() {
    return getIdentifier();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (identifier_ != null) {
      output.writeMessage(1, getIdentifier());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (identifier_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getIdentifier());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FindSuccessorResponse)) {
      return super.equals(obj);
    }
    FindSuccessorResponse other = (FindSuccessorResponse) obj;

    if (hasIdentifier() != other.hasIdentifier()) return false;
    if (hasIdentifier()) {
      if (!getIdentifier()
          .equals(other.getIdentifier())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIdentifier()) {
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FindSuccessorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FindSuccessorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FindSuccessorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FindSuccessorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FindSuccessorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FindSuccessorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FindSuccessorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FindSuccessorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FindSuccessorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FindSuccessorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FindSuccessorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FindSuccessorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FindSuccessorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chord.FindSuccessorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chord.FindSuccessorResponse)
      FindSuccessorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChordNodeProto.internal_static_chord_FindSuccessorResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChordNodeProto.internal_static_chord_FindSuccessorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FindSuccessorResponse.class, Builder.class);
    }

    // Construct using net.grpc.chord.FindSuccessorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (identifierBuilder_ == null) {
        identifier_ = null;
      } else {
        identifier_ = null;
        identifierBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChordNodeProto.internal_static_chord_FindSuccessorResponse_descriptor;
    }

    @Override
    public FindSuccessorResponse getDefaultInstanceForType() {
      return FindSuccessorResponse.getDefaultInstance();
    }

    @Override
    public FindSuccessorResponse build() {
      FindSuccessorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FindSuccessorResponse buildPartial() {
      FindSuccessorResponse result = new FindSuccessorResponse(this);
      if (identifierBuilder_ == null) {
        result.identifier_ = identifier_;
      } else {
        result.identifier_ = identifierBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FindSuccessorResponse) {
        return mergeFrom((FindSuccessorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FindSuccessorResponse other) {
      if (other == FindSuccessorResponse.getDefaultInstance()) return this;
      if (other.hasIdentifier()) {
        mergeIdentifier(other.getIdentifier());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FindSuccessorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FindSuccessorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Identifier identifier_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Identifier, Identifier.Builder, IdentifierOrBuilder> identifierBuilder_;
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public boolean hasIdentifier() {
      return identifierBuilder_ != null || identifier_ != null;
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public Identifier getIdentifier() {
      if (identifierBuilder_ == null) {
        return identifier_ == null ? Identifier.getDefaultInstance() : identifier_;
      } else {
        return identifierBuilder_.getMessage();
      }
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public Builder setIdentifier(Identifier value) {
      if (identifierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        identifier_ = value;
        onChanged();
      } else {
        identifierBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public Builder setIdentifier(
        Identifier.Builder builderForValue) {
      if (identifierBuilder_ == null) {
        identifier_ = builderForValue.build();
        onChanged();
      } else {
        identifierBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public Builder mergeIdentifier(Identifier value) {
      if (identifierBuilder_ == null) {
        if (identifier_ != null) {
          identifier_ =
            Identifier.newBuilder(identifier_).mergeFrom(value).buildPartial();
        } else {
          identifier_ = value;
        }
        onChanged();
      } else {
        identifierBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public Builder clearIdentifier() {
      if (identifierBuilder_ == null) {
        identifier_ = null;
        onChanged();
      } else {
        identifier_ = null;
        identifierBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public Identifier.Builder getIdentifierBuilder() {
      
      onChanged();
      return getIdentifierFieldBuilder().getBuilder();
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    public IdentifierOrBuilder getIdentifierOrBuilder() {
      if (identifierBuilder_ != null) {
        return identifierBuilder_.getMessageOrBuilder();
      } else {
        return identifier_ == null ?
            Identifier.getDefaultInstance() : identifier_;
      }
    }
    /**
     * <code>.chord.Identifier identifier = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Identifier, Identifier.Builder, IdentifierOrBuilder>
        getIdentifierFieldBuilder() {
      if (identifierBuilder_ == null) {
        identifierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Identifier, Identifier.Builder, IdentifierOrBuilder>(
                getIdentifier(),
                getParentForChildren(),
                isClean());
        identifier_ = null;
      }
      return identifierBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chord.FindSuccessorResponse)
  }

  // @@protoc_insertion_point(class_scope:chord.FindSuccessorResponse)
  private static final FindSuccessorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FindSuccessorResponse();
  }

  public static FindSuccessorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FindSuccessorResponse>
      PARSER = new com.google.protobuf.AbstractParser<FindSuccessorResponse>() {
    @Override
    public FindSuccessorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FindSuccessorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FindSuccessorResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FindSuccessorResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public FindSuccessorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

