// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

/**
 * Protobuf type {@code chord.Identifier}
 */
public  final class Identifier extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chord.Identifier)
    IdentifierOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Identifier.newBuilder() to construct.
  private Identifier(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Identifier() {
    iP_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Identifier(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            iP_ = s;
            break;
          }
          case 16: {

            port_ = input.readInt32();
            break;
          }
          case 24: {

            iD_ = input.readInt32();
            break;
          }
          case 34: {
            Builder subBuilder = null;
            if (predecessor_ != null) {
              subBuilder = predecessor_.toBuilder();
            }
            predecessor_ = input.readMessage(Identifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(predecessor_);
              predecessor_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            Builder subBuilder = null;
            if (successor_ != null) {
              subBuilder = successor_.toBuilder();
            }
            successor_ = input.readMessage(Identifier.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(successor_);
              successor_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChordNodeProto.internal_static_chord_Identifier_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChordNodeProto.internal_static_chord_Identifier_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Identifier.class, Builder.class);
  }

  public static final int IP_FIELD_NUMBER = 1;
  private volatile Object iP_;
  /**
   * <code>string IP = 1;</code>
   */
  public String getIP() {
    Object ref = iP_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      iP_ = s;
      return s;
    }
  }
  /**
   * <code>string IP = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIPBytes() {
    Object ref = iP_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      iP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 2;
  private int port_;
  /**
   * <code>int32 port = 2;</code>
   */
  public int getPort() {
    return port_;
  }

  public static final int ID_FIELD_NUMBER = 3;
  private int iD_;
  /**
   * <code>int32 ID = 3;</code>
   */
  public int getID() {
    return iD_;
  }

  public static final int PREDECESSOR_FIELD_NUMBER = 4;
  private Identifier predecessor_;
  /**
   * <code>.chord.Identifier predecessor = 4;</code>
   */
  public boolean hasPredecessor() {
    return predecessor_ != null;
  }
  /**
   * <code>.chord.Identifier predecessor = 4;</code>
   */
  public Identifier getPredecessor() {
    return predecessor_ == null ? Identifier.getDefaultInstance() : predecessor_;
  }
  /**
   * <code>.chord.Identifier predecessor = 4;</code>
   */
  public IdentifierOrBuilder getPredecessorOrBuilder() {
    return getPredecessor();
  }

  public static final int SUCCESSOR_FIELD_NUMBER = 5;
  private Identifier successor_;
  /**
   * <code>.chord.Identifier successor = 5;</code>
   */
  public boolean hasSuccessor() {
    return successor_ != null;
  }
  /**
   * <code>.chord.Identifier successor = 5;</code>
   */
  public Identifier getSuccessor() {
    return successor_ == null ? Identifier.getDefaultInstance() : successor_;
  }
  /**
   * <code>.chord.Identifier successor = 5;</code>
   */
  public IdentifierOrBuilder getSuccessorOrBuilder() {
    return getSuccessor();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, iP_);
    }
    if (port_ != 0) {
      output.writeInt32(2, port_);
    }
    if (iD_ != 0) {
      output.writeInt32(3, iD_);
    }
    if (predecessor_ != null) {
      output.writeMessage(4, getPredecessor());
    }
    if (successor_ != null) {
      output.writeMessage(5, getSuccessor());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, iP_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, port_);
    }
    if (iD_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, iD_);
    }
    if (predecessor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getPredecessor());
    }
    if (successor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSuccessor());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Identifier)) {
      return super.equals(obj);
    }
    Identifier other = (Identifier) obj;

    if (!getIP()
        .equals(other.getIP())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (getID()
        != other.getID()) return false;
    if (hasPredecessor() != other.hasPredecessor()) return false;
    if (hasPredecessor()) {
      if (!getPredecessor()
          .equals(other.getPredecessor())) return false;
    }
    if (hasSuccessor() != other.hasSuccessor()) return false;
    if (hasSuccessor()) {
      if (!getSuccessor()
          .equals(other.getSuccessor())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIP().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getID();
    if (hasPredecessor()) {
      hash = (37 * hash) + PREDECESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getPredecessor().hashCode();
    }
    if (hasSuccessor()) {
      hash = (37 * hash) + SUCCESSOR_FIELD_NUMBER;
      hash = (53 * hash) + getSuccessor().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Identifier parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Identifier parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Identifier parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Identifier parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Identifier parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Identifier parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Identifier parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Identifier parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Identifier parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Identifier parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Identifier parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Identifier parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Identifier prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chord.Identifier}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chord.Identifier)
      IdentifierOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChordNodeProto.internal_static_chord_Identifier_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChordNodeProto.internal_static_chord_Identifier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Identifier.class, Builder.class);
    }

    // Construct using net.grpc.chord.Identifier.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      iP_ = "";

      port_ = 0;

      iD_ = 0;

      if (predecessorBuilder_ == null) {
        predecessor_ = null;
      } else {
        predecessor_ = null;
        predecessorBuilder_ = null;
      }
      if (successorBuilder_ == null) {
        successor_ = null;
      } else {
        successor_ = null;
        successorBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChordNodeProto.internal_static_chord_Identifier_descriptor;
    }

    @Override
    public Identifier getDefaultInstanceForType() {
      return Identifier.getDefaultInstance();
    }

    @Override
    public Identifier build() {
      Identifier result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Identifier buildPartial() {
      Identifier result = new Identifier(this);
      result.iP_ = iP_;
      result.port_ = port_;
      result.iD_ = iD_;
      if (predecessorBuilder_ == null) {
        result.predecessor_ = predecessor_;
      } else {
        result.predecessor_ = predecessorBuilder_.build();
      }
      if (successorBuilder_ == null) {
        result.successor_ = successor_;
      } else {
        result.successor_ = successorBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Identifier) {
        return mergeFrom((Identifier)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Identifier other) {
      if (other == Identifier.getDefaultInstance()) return this;
      if (!other.getIP().isEmpty()) {
        iP_ = other.iP_;
        onChanged();
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (other.getID() != 0) {
        setID(other.getID());
      }
      if (other.hasPredecessor()) {
        mergePredecessor(other.getPredecessor());
      }
      if (other.hasSuccessor()) {
        mergeSuccessor(other.getSuccessor());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Identifier parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Identifier) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object iP_ = "";
    /**
     * <code>string IP = 1;</code>
     */
    public String getIP() {
      Object ref = iP_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        iP_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string IP = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIPBytes() {
      Object ref = iP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        iP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string IP = 1;</code>
     */
    public Builder setIP(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      iP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string IP = 1;</code>
     */
    public Builder clearIP() {

      iP_ = getDefaultInstance().getIP();
      onChanged();
      return this;
    }
    /**
     * <code>string IP = 1;</code>
     */
    public Builder setIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      iP_ = value;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 2;</code>
     */
    public Builder setPort(int value) {

      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 2;</code>
     */
    public Builder clearPort() {

      port_ = 0;
      onChanged();
      return this;
    }

    private int iD_ ;
    /**
     * <code>int32 ID = 3;</code>
     */
    public int getID() {
      return iD_;
    }
    /**
     * <code>int32 ID = 3;</code>
     */
    public Builder setID(int value) {

      iD_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ID = 3;</code>
     */
    public Builder clearID() {

      iD_ = 0;
      onChanged();
      return this;
    }

    private Identifier predecessor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Identifier, Builder, IdentifierOrBuilder> predecessorBuilder_;
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public boolean hasPredecessor() {
      return predecessorBuilder_ != null || predecessor_ != null;
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public Identifier getPredecessor() {
      if (predecessorBuilder_ == null) {
        return predecessor_ == null ? Identifier.getDefaultInstance() : predecessor_;
      } else {
        return predecessorBuilder_.getMessage();
      }
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public Builder setPredecessor(Identifier value) {
      if (predecessorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        predecessor_ = value;
        onChanged();
      } else {
        predecessorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public Builder setPredecessor(
        Builder builderForValue) {
      if (predecessorBuilder_ == null) {
        predecessor_ = builderForValue.build();
        onChanged();
      } else {
        predecessorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public Builder mergePredecessor(Identifier value) {
      if (predecessorBuilder_ == null) {
        if (predecessor_ != null) {
          predecessor_ =
            Identifier.newBuilder(predecessor_).mergeFrom(value).buildPartial();
        } else {
          predecessor_ = value;
        }
        onChanged();
      } else {
        predecessorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public Builder clearPredecessor() {
      if (predecessorBuilder_ == null) {
        predecessor_ = null;
        onChanged();
      } else {
        predecessor_ = null;
        predecessorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public Builder getPredecessorBuilder() {

      onChanged();
      return getPredecessorFieldBuilder().getBuilder();
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    public IdentifierOrBuilder getPredecessorOrBuilder() {
      if (predecessorBuilder_ != null) {
        return predecessorBuilder_.getMessageOrBuilder();
      } else {
        return predecessor_ == null ?
            Identifier.getDefaultInstance() : predecessor_;
      }
    }
    /**
     * <code>.chord.Identifier predecessor = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Identifier, Builder, IdentifierOrBuilder>
        getPredecessorFieldBuilder() {
      if (predecessorBuilder_ == null) {
        predecessorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Identifier, Builder, IdentifierOrBuilder>(
                getPredecessor(),
                getParentForChildren(),
                isClean());
        predecessor_ = null;
      }
      return predecessorBuilder_;
    }

    private Identifier successor_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Identifier, Builder, IdentifierOrBuilder> successorBuilder_;
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public boolean hasSuccessor() {
      return successorBuilder_ != null || successor_ != null;
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public Identifier getSuccessor() {
      if (successorBuilder_ == null) {
        return successor_ == null ? Identifier.getDefaultInstance() : successor_;
      } else {
        return successorBuilder_.getMessage();
      }
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public Builder setSuccessor(Identifier value) {
      if (successorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        successor_ = value;
        onChanged();
      } else {
        successorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public Builder setSuccessor(
        Builder builderForValue) {
      if (successorBuilder_ == null) {
        successor_ = builderForValue.build();
        onChanged();
      } else {
        successorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public Builder mergeSuccessor(Identifier value) {
      if (successorBuilder_ == null) {
        if (successor_ != null) {
          successor_ =
            Identifier.newBuilder(successor_).mergeFrom(value).buildPartial();
        } else {
          successor_ = value;
        }
        onChanged();
      } else {
        successorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public Builder clearSuccessor() {
      if (successorBuilder_ == null) {
        successor_ = null;
        onChanged();
      } else {
        successor_ = null;
        successorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public Builder getSuccessorBuilder() {

      onChanged();
      return getSuccessorFieldBuilder().getBuilder();
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    public IdentifierOrBuilder getSuccessorOrBuilder() {
      if (successorBuilder_ != null) {
        return successorBuilder_.getMessageOrBuilder();
      } else {
        return successor_ == null ?
            Identifier.getDefaultInstance() : successor_;
      }
    }
    /**
     * <code>.chord.Identifier successor = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Identifier, Builder, IdentifierOrBuilder>
        getSuccessorFieldBuilder() {
      if (successorBuilder_ == null) {
        successorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Identifier, Builder, IdentifierOrBuilder>(
                getSuccessor(),
                getParentForChildren(),
                isClean());
        successor_ = null;
      }
      return successorBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chord.Identifier)
  }

  // @@protoc_insertion_point(class_scope:chord.Identifier)
  private static final Identifier DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Identifier();
  }

  public static Identifier getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Identifier>
      PARSER = new com.google.protobuf.AbstractParser<Identifier>() {
    @Override
    public Identifier parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Identifier(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Identifier> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Identifier> getParserForType() {
    return PARSER;
  }

  @Override
  public Identifier getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

