// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

public interface NullRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chord.NullRequest)
    com.google.protobuf.MessageOrBuilder {
}
