// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

public interface NullResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chord.NullResponse)
    com.google.protobuf.MessageOrBuilder {
}
