// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

public interface TellmePredecessorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chord.TellmePredecessorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ID = 1;</code>
   */
  int getID();
}
