// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chordNodeService.proto

package net.grpc.chord;

public interface TellmePredecessorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chord.TellmePredecessorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chord.Identifier identifier = 1;</code>
   */
  boolean hasIdentifier();
  /**
   * <code>.chord.Identifier identifier = 1;</code>
   */
  Identifier getIdentifier();
  /**
   * <code>.chord.Identifier identifier = 1;</code>
   */
  IdentifierOrBuilder getIdentifierOrBuilder();
}
